development:
  adapter: postgresql
  encoding: utf8
  database: piadas_nerds_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: piadas_nerds_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: piadas_nerds_production
  pool: 5
  username:
  password:
